apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icupa.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "icupa.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared-config
data:
  {{- range $key, $value := .Values.global.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
