apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icupa.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "icupa.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  {{- range $key, $value := .Values.global.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
