apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: icupa
resources:
  - namespace.yaml
  - configmap-apps.yaml
  - secret-apps-example.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - meilisearch-deployment.yaml
  - mailhog-deployment.yaml
  - minio-statefulset.yaml
  - agents-service-deployment.yaml
  - admin-deployment.yaml
  - client-deployment.yaml
  - vendor-deployment.yaml
  - web-deployment.yaml
  - voice-agent-deployment.yaml
  - ocr-converter-deployment.yaml
  - ecotrips-deployment.yaml
